### ISSUE TITLE
Chunk Models - Unknown/Invalid Poly Type

### ISSUE THREAD

**Issue by ItsEasyActually** [X-Hax/SonicAdventureBlenderIO#18]
[The Ninja file found here](https://github.com/user-attachments/files/15959972/013_fldManshipD_00.zip) produces the following error when imported:
`An error occured while importing 013_fldManshipD_00.nj
Traceback (most recent call last):
  File "C:\Users\iea\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SonicAdventureBlenderIO\source\register\operators\base.py", line 26, in execute
    return self._execute(context)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iea\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SonicAdventureBlenderIO\source\register\operators\import_operators.py", line 110, in _execute
    raise error
  File "C:\Users\iea\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SonicAdventureBlenderIO\source\register\operators\import_operators.py", line 106, in _execute
    import_data = SAIO_NET.MODEL.Import(
                  ^^^^^^^^^^^^^^^^^^^^^^
System.FormatException: Poly chunk type is invalid: 205`

The data is able to be opened in SAMDL, so it does not appear to be an unknown poly type from the documentation. It's unclear if the error is a result of actually being an invalid poly type or if there may be a read error occurring when attempting to parse the Poly chunks in the file.

**Comment by Justin113D** [comment]
Fixed in release 2.2.0
