### ISSUE TITLE
When exporting landtable, I get this error:

### ISSUE THREAD

**Issue by Chris2918** [X-Hax/SonicAdventureBlenderIO#3]
Traceback (most recent call last):
  File "C:\Users\lccji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SonicAdventureBlenderIO\source\register\operators\base.py", line 26, in execute
    return self._execute(context)
  File "C:\Users\lccji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SonicAdventureBlenderIO\source\register\operators\base_export_operators.py", line 39, in _execute
    return self.export(context)
  File "C:\Users\lccji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SonicAdventureBlenderIO\source\register\operators\base_export_operators.py", line 80, in export
    return self.export_models(context, objects)
  File "C:\Users\lccji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SonicAdventureBlenderIO\source\register\operators\export_operators.py", line 198, in export_models
    evaluator.evaluate(objects)
  File "C:\Users\lccji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SonicAdventureBlenderIO\source\exporting\o_landtable.py", line 123, in evaluate
    self._eval_mesh_models()
  File "C:\Users\lccji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SonicAdventureBlenderIO\source\exporting\o_landtable.py", line 108, in _eval_mesh_models
    self._mesh_structs = o_mesh.ModelMesh.evaluate_models(
  File "C:\Users\lccji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SonicAdventureBlenderIO\source\exporting\o_mesh.py", line 439, in evaluate_models
    weighted_buffer = mesh.convert_to_weighted_buffer(
  File "C:\Users\lccji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SonicAdventureBlenderIO\source\exporting\o_mesh.py", line 397, in convert_to_weighted_buffer
    vertices = self._get_raw_verts()
  File "C:\Users\lccji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SonicAdventureBlenderIO\source\exporting\o_mesh.py", line 314, in _get_raw_verts
    normals = self._get_normals()
  File "C:\Users\lccji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SonicAdventureBlenderIO\source\exporting\o_mesh.py", line 215, in _get_normals
    return ModelMesh.get_normals(self._evaluated_mesh)
  File "C:\Users\lccji\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SonicAdventureBlenderIO\source\exporting\o_mesh.py", line 204, in get_normals
    for loop, normal in zip(mesh.loops, mesh.corner_normals):
AttributeError: 'Mesh' object has no attribute 'corner_normals'. Did you mean: 'vertex_normals'?
AttributeError: 'Mesh' object has no attribute 'corner_normals'. Did you mean: 'vertex_normals'?

**Comment by Justin113D** [comment]
You are using blender 3.3
You need to use blender 3.6
